import type { Metadata } from "next";
import { Geist, Geist_Mono, Archivo } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/context/Appcontext";
import LayoutWrapper from "@/components/LayoutWrapper/LayoutWrapper";
import ApolloWrapper from "./providers/ApolloWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fontArchivo = Archivo({
  variable: "--font-Archivo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontArchivo.variable} antialiased`}
      >
        <ApolloWrapper>
          <AppProvider>
            <div className="min-h-screen flex flex-col">
              <LayoutWrapper>{children}</LayoutWrapper>
            </div>
          </AppProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
